### ISSUE TITLE
New Posts ボタンタップ時の挙動を改善したい

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#1]
- New Posts ボタンタップ時にスクロール位置がトップになったほうがいいのでは？
- New Posts ボタンタップ時の差分更新で（たぶん）削除が反映されていない。

**Comment by baisony** [comment]
- New Posts ボタンタップ時にスクロール位置がトップになったほうがいいのでは？
これについては切り替えのニーズがあるみたいで、具体的には
・現在のスクロール位置を維持したまま上に新規postを追加したい
・TL更新時に上へスクロールしたい
の2派があるらしく、これらを切り替えられると良きです

**Comment by so-asano** [comment]
@baisony 

本イシューに関連して以下の修正をおこないます。

- 更新がない場合は New Posts ボタンを出さない。

**Comment by baisony** [comment]
@so-asano 
TL更新時における一番上へのスクロール実装を確認しました。ありがとうございます。

それに伴って、一旦は「・TL更新時に上へスクロールする」のみで行きます。

**Comment by so-asano** [comment]
@baisony 

本イシューの以下の内容ですが、いったん対応せずでいいのではないかとおもいます:

- New Posts ボタンタップ時の差分更新で（たぶん）削除が反映されていない。

理由は、取得する更新差分からは既存タイムラインから削除されたぶんがわからないから、です。
もし、よい方法がわかったら新規にイシューを立てるということでいいのではないかと。

**Comment by baisony** [comment]
@so-asano 
こちら、差分更新における削除反映を除いて、すべての改善と修正を確認しましたので、マージいたします。
また当該の問題については、別途issueを立てます
