### ISSUE TITLE
NirvanaUI スワイプでフィードを切り替えると連続切替になる場合が発生

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#103]
## 現象

NirvanaUI でフィードを左右に切り替えていると、1回のスワイプで手を離しても連続してスワイプ動作を繰り返してしまう。この状態になると、再びタッチしてスワイプを止めるような動作をしないと、先頭や最後のフィードまで止まらない状態になる。

## 発生条件

長くスワイプするのではなく、短くスワイプした場合に発生しやすいと思われたが、可能性としては、スワイプ操作時に指を話すときに、指のタッチが完全に離れる前に逆方向に動かす動作が入ると、起こるのではないか。

## 添付動画

iPhone 15 Pro Max iOS 17 Safari にて、Bluetoothマウスを接続し、ポインタ(青丸)を表示した状態で操作し、現象を起こした画面集緑動画です。

https://github.com/baisony/ucho-ten/assets/143017/3386d4d5-6d54-4ecf-b229-19b4fa434a77

**Comment by so-asano** [comment]
@baisony 

調査への協力よろしくお願いします。

**Comment by baisony** [comment]
https://github.com/nolimits4web/swiper/issues/6822

こちらが関係していそうです。

**Comment by baisony** [comment]
[https://github[.]com/nolimits4web/swiper/issues/6822](https://github.com/nolimits4web/swiper/issues/6822)

**Comment by baisony** [comment]
こちらが関係していそうです。

**Comment by baisony** [comment]
#190 にて修正されましたのでクローズいたします。
