### ISSUE TITLE
ViewPostCardにおいて画像が複数枚添付されている場合、NextUIのスクロールシャドウが効かない

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#104]

**Comment by so-asano** [comment]
@baisony 

これとは直接関係ないですが、今の涅槃 UI でもナビゲーションバー上でスクロールシャドウ効かなくて外してます。
スクロールシャドウ、重いだけな気がするんですが必要ですかね？

**Comment by baisony** [comment]
@so-asano 
横に画像がある(スクロールの余地がある)ということを視覚的に分かりやすいようにスクロールシャドウを設定しているので、必要だと思っています。

現在のnirvana-uiブランチをみる限り、タイトルの問題は再現されていないのですが、修正していただけたということでよろしいですか？

**Comment by baisony** [comment]
こちら、修正を確認しましたのでクローズいたします。

@so-asano 
ご対応いただきありがとうございました。
