### ISSUE TITLE
inboxタブにおけるlistNotificationが止まらない

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#108]
再現法を調査中

1. inboxタブを開く
2. consoleにnullが表示される前に他のタブへ移動する。(例ホームや検索画面など)
3. 無限に通知を取得し続ける

おそらく、useEffectあたりのアンマウントがうまく行っていないからだと思われる。

再現動画はdiscordへ

**Comment by so-asano** [comment]
@baisony 

これは気づいていました。`useState` だとすぐに値が更新されないせいでバグが起きていそうです。修正しておきます。

**Comment by so-asano** [comment]
@baisony 

有頂天で表示可能な通知が 20 になるまでは取得をつづける仕様で修正しました。

**Comment by baisony** [comment]
@so-asano さん
当該修正のpull requestをマージしましたのでクローズいたします。
ありがとうございました。
