### ISSUE TITLE
マジックナンバーと思われる数値の定数化

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#116]
## 問題点

全コードを見たわけではありませんが、ポスト上限文字数や、添付画像の最大データサイズなどの、いわゆるマジックナンバーがコード内に散見されます。

全コード中で1箇所はともかく、一つのファイル中に何度も同じ数値が直書きされているのは、間違いのもととなりやすいです。

## 対応

定数化もしくは取得メソッド化して、共通にさせた方がいいでしょう。

**Comment by so-asano** [comment]
@henoya @baisony 

ディレクトリをつくって、そこに用途別に定数をまとめていれたファイルを作れないかな、とおもっています。
これは別件ですが、型やインターフェイスについても同様にしたいな、と。

参考 URL:
- https://wityan.medium.com/next-js-project-structure-1531610bed71 （ディレクトリ構成、Next 13 ではないけど）

**Comment by baisony** [comment]
#326 で対応するためクローズいたします。
