### ISSUE TITLE
デザインの不具合

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#117]
- [x] 引用ポストがはみ出ている。
- [x] モバイルでポストに触れると背景色が変わるが必要なデザインとはおもえない。
- [x] "Reposted by" の前にリポストのアイコンがあったほうがよいのでは？
- [x] ディスプレイネームとハンドルが長い場合、日時表示とかぶる。

**Comment by baisony** [comment]
@so-asano 
Reposted byの前にリポストのアイコン表示を上記コミットで追加しておきました。

**Comment by baisony** [comment]
- モバイルでポストに触れると背景色が変わるが必要なデザインとはおもえない。
-  ディスプレイネームとハンドルが長い場合、日時表示とかぶる。
以上二つの問題を #217 にて修正しました。

**Comment by baisony** [comment]
こちら修正しましたのでクローズいたします。
