### ISSUE TITLE
ポスト作成で、本文の先頭に空白などがあると、リンクなどのrich text の対象範囲がずれる

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#118]
## 現象

ポスト、もしくはリプライ投稿画面で、先頭に削除対象の空白や改行があると、その後に入れたrich textでの範囲対象となるリンク(およびメンションなども)の範囲がずれる。

![image](https://github.com/baisony/ucho-ten/assets/143017/f2f3be6a-499b-4236-a901-258fe13999af)

## 原因

rich textテキストの範囲計算が、空白文字の除去がされていない文字列を対象にされている

**Comment by baisony** [comment]
@henoya 
こちら修正を確認しましたので、クローズいたします。
ありがとうございました。
