### ISSUE TITLE
"URL短縮の可能性があります。" が表示される条件が少しきついのでは

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#120]
## 現象

ポスト本文にリンクとして "yahoo.co.jp" や "Google.co.jp" と入力した場合に、ポスト後のカードのリンクには "?"アイコンが表示され、"URL短縮の可能性があります。" とヒントが表示される。

![image](https://github.com/baisony/ucho-ten/assets/143017/2584b1c8-7c4d-4f0d-877b-00cd98792e53)

## 対応

おそらくは、ポストテキスト中に "https://" 等と付いていないからではないかと思われる。

これをもって、"URL短縮の可能性があります。"という表示は、意味が違うかも。

**Comment by baisony** [comment]
@henoya こちらについて少し考えてみます。

**Comment by baisony** [comment]
@henoya 
こちらで修正 128ba8239a90fb24579c6b3a3a2e4f38ed6c4452 しましたのでクローズいたします。
ご報告ありがとうございました。
