### ISSUE TITLE
スマホにおけるノッチの部分の色を動的に変更したい

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#129]
現状は白い

**Comment by so-asano** [comment]
@baisony 

画像はうまくいかないかも。以前なんどやっても失敗した記憶があります。色ならできました。

**Comment by baisony** [comment]
@so-asano 
なるほど...。色で誤魔化すしかなさそうですね

**Comment by baisony** [comment]
ダークモードの時はblack lightモードはwhiteの方向でいきます。

**Comment by baisony** [comment]
こちら、systemのみだったら可能ですが、system light darkの3種類運用としているため現状難しく、実装方法が思いつき次第、再度issueを立てます。
