### ISSUE TITLE
ポスト削除の実装のやりなおし（涅槃 UI）

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#136]
#125 のポストの削除機能の実装ですが、 #134  での修正内容がこちらで並行しておこなっていたリファクタリングとかぶってしまったため、マージ時に大量のコンフリクトが発生し、やむを得ず Incoming Changes を破棄しました。
それにより、`feat/nirvana-ui` のほうでは同機能の再度の実装が必要になりました。

**Comment by so-asano** [comment]
@baisony 

対応よろしくお願いします。

**Comment by baisony** [comment]
@so-asano 
承知しました。
修正しますのでお待ちください

**Comment by baisony** [comment]
@so-asano こちら、再度の実装とマージを行いましたので、クローズいたします。
