### ISSUE TITLE
引用ポストの画像の表示を追加する

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#137]
- 引用ポストの画像が表示されない。
- 画像だけのポストを引用したりするケースや画像に言及しているケースがあるため、公式に準拠して表示すべきと考える。

**Comment by so-asano** [comment]
@baisony 

涅槃 UI では `ViewPostCard` のリファクタリングにより対応しました。

**Comment by baisony** [comment]
機能追加を確認しましたのでクローズいたします。
