### ISSUE TITLE
ポスト画面でブラウザで画面をリロードすると React のエラーが発生する

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#15]
今のところ原因は不明。

再現手順は以下のとおり:
1. タブバーのボタンをタップしてポスト画面に遷移。
2. その状態でブラウザをリロード。
3. デバッグモードだとエラーが出る。

**Comment by so-asano** [comment]
- `BrowserView` の使用が原因のようだが、対応方針は不明。

**Comment by baisony** [comment]
BrowserViewを廃止し、tailwindにてモバイルの判定を行ったことで修正されました。

**Comment by baisony** [comment]
マージしたのでクローズいたします。
