### ISSUE TITLE
SVG のレンダリングに時間がかかるので PNG に変更する

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#16]
画面リロード時にヘッダのロゴの描画が遅れるので、対応が必要だとおもいます。

**Comment by so-asano** [comment]
@baisony 

これクローズできない理由ってありましたっけ？

**Comment by baisony** [comment]
@so-asano 
私的には、pngより綺麗に、かつ画質の低下を招かないsvgでロゴを表示させたいと思ってます。
結局、レンダリング速度低下の原因がsvgであったことではなく、NextUIのImageタグを用いたことによるものなので、一旦svgのロゴを適用してみて、レンダリング時間に大きな差がなければsvgを使う方向でいきたいので、検証をお願いいたします。

その検証・(あれば)修正が完了したらクローズします。

**Comment by so-asano** [comment]
@baisony 

修正したブランチで検証しましたが、ぼくには違いがわかりませんでした。
結局は原因はちがったということで、svg のロゴを用いる方向でよいとおもいます。

**Comment by baisony** [comment]
@so-asano 
そうですね。
svgを用いることによる不都合が生じれば、またpngにするなど対応を取るので、こちらのブランチをマージし、クローズといたします。
