### ISSUE TITLE
postmodalにおいて、nを入力すると/postに遷移してしまう

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#164]

**Comment by baisony** [comment]
@so-asano 
追記：
/postでは再現せず、リプライモーダルにおいてnを入力すると再現するようです

**Comment by so-asano** [comment]
@baisony 

修正しました。

**Comment by baisony** [comment]
@so-asano 
こちらの修正を確認しました。
マージ済みですのでクローズいたします。
