### ISSUE TITLE
デザインに関連した修正

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#167]
- [x] 添付画像がひとつの場合は `ScrollShadow` を出さない。

**Comment by so-asano** [comment]
@baisony 

`ScrollShadow` の件、対応しました。

**Comment by baisony** [comment]
こちら修正を確認しましたのでクローズいたします。

@so-asano 
ご対応いただきありがとうございました。

**Comment by so-asano** [comment]
デザインに関連したバグがまだあるとおもうので、再オープンします。

**Comment by baisony** [comment]
別イシューを立てて対応いたします。
