### ISSUE TITLE
画面リロード時に背景画像が表示されないようにしたい

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#18]
再現方法:
1. タブバーのボタンでホーム画面に遷移。
2. ブラウザのリロードボタンをタップ。
3. 読み込み中に一瞬だけ背景画像がみえてしまう。

**Comment by so-asano** [comment]
@baisony 

こちらクローズできますか？

**Comment by baisony** [comment]
@so-asano 
すみません！マージしたのでクローズいたします。
