### ISSUE TITLE
"アバターなし" の画像を作成してほしい

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#185]
- `FontAwesome` の `faUser` を使うのはあまり筋がよくないとおもう。ロジックも無駄に複雑になっている。

**Comment by baisony** [comment]
画像を探しておきますー。

**Comment by so-asano** [comment]
@baisony 

フィードジェネレータの画像なし、あたりも必要そうですね。
どれくらいそういうのがあるかいちどまとめたほうがいいかも。

**Comment by baisony** [comment]
アバターなしが必要な箇所
・userのアイコン
・フィードのアイコン

**Comment by baisony** [comment]
こちらは落ち着いてからFontAwesomeIcon以外で実装したいため、今はPriority Lowといたします。
