### ISSUE TITLE
未ログイン時に検索画面の URL を入力するとログイン画面に遷移しない

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#188]
再現方法:

1. プライベートブラウジングや未ログイン状態で https://test.ucho-ten.net/search とアドレスバーにいれる。
2. 画面が検索画面のままになり、ログイン画面へとリダイレクトされない。

ログイン画面にリダイレクトされるのが正しい。

**Comment by baisony** [comment]
こちら修正しましたのでクローズいたします。
