### ISSUE TITLE
Safari でもフォントに Noto Sans を適用したい

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#2]
- Emoji 対応で Safari のフォントが変わってしまったとのこと。

一時的な案
完全な Emoji 対応は大変そうなので、いったん Emoji 対応を切るのはいかですかね？
それでもほとんどの Emoji は表示されるはずなので。
Noto Sans が表示されないことのほうが問題な気がします。

**Comment by so-asano** [comment]
@baisony 

本イシューどうしますか？ ぼくは暫定案で対応したいかなとおもってます。現状、表示が見苦しいので。

**Comment by baisony** [comment]
noto sans jpで表示されない原因として、emoji fontを設定している影響があるので、そちらを一旦消去いたします。

**Comment by baisony** [comment]
問題の修正が完了したので、クローズいたします
