### ISSUE TITLE
ナビゲーションバーのメニューの再実装

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#201]
- 選択されたものへのスクロールによる表示に問題があり（たとえば最も右の要素を選択したとき、その要素が最も左に表示されてしまう。添付ファイル参照）、いま使用しているライブラリだとうまく調整ができない。
- より柔軟な表示が可能な `Swiper` を用いた再実装を検討中。

![image](https://github.com/baisony/ucho-ten/assets/770175/b8f1fa91-53da-456d-867a-f2e271bccb4d)

**Comment by baisony** [comment]
@so-asano 
こちらの改善を確認したため、マージいたしました。
ご対応いただきありがとうございました。
