### ISSUE TITLE
コードのフォーマットを統一したい

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#21]
- コードのフォーマット設定を統一し、自動フォーマットすれば無駄な工数が削減できる。

**Comment by so-asano** [comment]
@baisony さんは WebStorm, @so-asano は VS Code を使っているため、その点の考慮が必要。

**Comment by baisony** [comment]
webStormにおいては、以下のリンク参照
https://pleiades.io/help/webstorm/prettier.html

また、webstormが.prettierrcを認識しないときは、リポジトリをcloneしなおし、pnpm install をすると再認識する模様

**Comment by baisony** [comment]
mergeしたのでクローズいたします
