### ISSUE TITLE
リストを Virtuoso で再実装する

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#211]
- [x] inbox
- [x] カスタムフィード（フィードジェネレータ）
- [x] ユーザプロフィール
- [x] 検索

（後ほど追記する）

**Comment by so-asano** [comment]
> フィードジェネレータ画面のユーザ検索を Virtuoso のリストで実装

コミットメッセージをミスりました。
正しくは、"フィードジェネレータ画面を Virtuoso のリストで実装" です。

**Comment by baisony** [comment]
こちらの改善を確認しました。
ご対応いただきありがとうございました。
