### ISSUE TITLE
タイムラインで先頭のポストがダミー扱いされて表示されていない

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#212]
- `Virtuoso` で最上部にパディングを入れる必要から、配列の先頭のデータをダミーとして扱っていた。
- ところが、タイムラインの配列の先頭にダミーデータを入れ忘れており、先頭のポストがダミーとして扱われ、表示されていなかった。

**Comment by baisony** [comment]
#213 にてこちらの問題の改善を確認いたしましたのでクローズします。

ご対応いただきありがとうございました。
