### ISSUE TITLE
リンクカードにサムネイルの存在しない場合も画像を表示しようとしている

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#214]
- リンクカードにはサムネイルの存在しないものがある。
- そういった場合でも画像を表示しようとているため、画像がリンク切れの状態で表示されてしまっている。
- リンクカードにサムネイルが存在しない場合は画像表示なしとするべきではないか。

**Comment by baisony** [comment]
こちらのプルリクを確認しまして、問題ありませんでしたのでマージいたしました。

ご対応いただき、ありがとうございます。
