### ISSUE TITLE
フィードタブが横スクロールが必要で使いにくい

### ISSUE THREAD

**Issue by nostr-bluesky** [baisony/ucho-ten#23]
フィードタブが横スクロールが必要で使いにくい

**Comment by nostr-bluesky** [comment]
スマホからアクセスする人だけではないし，
パソコンでもタッチパッドがあるパソコンを使ってる人だけでもない

**Comment by baisony** [comment]
@nostr-bluesky 今はスマホ版デザイン実装段階なのでパソコンのことはあまり考えていないのですが、パソコン操作用になにか考えておきますー

**Comment by nostr-bluesky** [comment]
スマホ版だったのか！

**Comment by nostr-bluesky** [comment]
ずっとMacでみてた

**Comment by nostr-bluesky** [comment]
これからはスマホでみるわー

**Comment by nostr-bluesky** [comment]
このデザインでいくのなら公式クライアントと同じようなUIストーリーがいいと思います．

左端にツールボックス的なものが来る．右から左にフリックすると，フィードが切り替わっていく．

**Comment by so-asano** [comment]
@nostr-bluesky 

本イシューですが、誤解にもとづくものということでクローズでいいでしょうか？

**Comment by nostr-bluesky** [comment]
へーい

**Comment by so-asano** [comment]
@baisony 

だそうですので、クローズしますか。

**Comment by baisony** [comment]
@so-asano @nostr-bluesky 
こちら、涅槃UIにて実装が完了しましたので、クローズいたします。
