### ISSUE TITLE
リプライ作成画面で、言語選択メニューがいったん上に延びて、下向きに変わる

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#237]
## 現象

リプライ作成画面(ポスト画面でも？) で、言語選択メニューを表示させると、言語メニューがいったん上に向けて表示され、その後下向きに表示しなおされる。

一回下向きに憑依されると、その後は表示させなおしても下向きのままになるが、ブラウザの再読み込みをおこなうと、一度だけ上向きに表示される現象が起きる。

https://github.com/baisony/ucho-ten/assets/143017/ef940f32-9f4a-472c-bda0-b7d8b62b69d0

**Comment by baisony** [comment]
@henoya 
報告ありがとうございます。
おそらく、NextUIのDropdownのplacementの指定をbottomにすると収まるかと思います。
修正までお待ちください

**Comment by baisony** [comment]
@henoya 
こちらについて、上記の方法でやってみたものの、改善しませんでした。
NextUIの仕様かと思われますので、一旦pendingとさせていただきます。
