### ISSUE TITLE
検索の挙動

### ISSUE THREAD

**Issue by nostr-bluesky** [baisony/ucho-ten#24]
メイン画面の状態のままで検索バーを表示した方が一貫性があるのでは？

**Comment by so-asano** [comment]
@nostr-bluesky

メイン画面のまま、というのはどういうことですか？

**Comment by nostr-bluesky** [comment]
タイムラインから検索専用の空の画面鬼飛ばないようにするということです

**Comment by baisony** [comment]
これについては新しくパーツを追加しましたのでご確認ください。
