### ISSUE TITLE
/postで投稿をしたのち、homeに戻った際に自分の投稿が反映されていない

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#247]
@so-asano こちらも併せてご確認ください。よろしくお願いします。

**Comment by so-asano** [comment]
これはバグじゃないです。タイミングの問題なので。
仕様の問題です。仕様を決めてください。

**Comment by baisony** [comment]
@so-asano 
/postやpostmodalにおいて投稿を送信してhomeに戻るとき、タイムラインを強制更新かけて、あるだけ新規ポストを反映する方針でお願いします。

**Comment by baisony** [comment]
こちらの問題は #248 によって併せて修正されましたのでクローズいたします。
