### ISSUE TITLE
なぜ投稿を連続体デザインに変更したのか．

### ISSUE THREAD

**Issue by nostr-bluesky** [baisony/ucho-ten#25]
なぜ投稿を連続体デザインに変更したのか．角丸カード配置デザインにはもどさなくていいので，例えば投稿間数ミリ開けて背景の青空が少し見えるようにするのはどうか．

何ミリ開けるかは，吟味が必要．

**Comment by baisony** [comment]
@nostr-bluesky 今後実装する、パソコンデザインにおいては非連続的デザインにはしますが、スマホデザインでは吟味が必要そうです。
なにせ画面が小さく、チカチカする可能性があるので、実験用に間隔を設定する欄を作って気軽に試せるようにしたいと思います

**Comment by so-asano** [comment]
@baisony @nostr-bluesky 

検証用のブランチつくって試してみましょうか？

**Comment by baisony** [comment]
@so-asano 
そうですね。
ViewPostCardに対してmarginBottomの数値を小数点単位で設定できるようにしましょうか。

**Comment by so-asano** [comment]
@baisony @nostr-bluesky 

では検証してみてから判断しましょう。

**Comment by baisony** [comment]
@nostr-bluesky 
こちらの試験用機能は実装が一通り終わって取り掛かりますので、5日前後時間をいただければ嬉しいです。

**Comment by nostr-bluesky** [comment]
スマホ用と知らずにキレてました．

連続体デザインについてですが，スマホだとちと話がかわってきます．

ただ，個別投稿の粒立ち感は表現したいところです．

**Comment by nostr-bluesky** [comment]
まだ着手できてないだけと思いますが，タイポグラフィーの問題があると思います．

文字サイズや太さ、いろ，アイコンの大きさなどです．

**Comment by so-asano** [comment]
@nostr-bluesky 

> まだ着手できてないだけと思いますが，タイポグラフィーの問題があると思います．
> 文字サイズや太さ、いろ，アイコンの大きさなどです．

デザインにかんしてご指摘がありましたら、別イシューを立ててまとめてかいたもらえるとたすかります。
よろしくお願いします。
