### ISSUE TITLE
タブバーボタンの挙動の改善

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#257]
以下、提案です:

- ホーム - 選択状態でのタップにより最も左のフィードに移動、~~最上部へスクロールさせる~~。
- 検索 - 選択状態でのタップにより検索状態をクリアし、検索トップへと遷移させる。
- Inbox - 選択状態でのタップにより強制で更新をおこない、最上部へとスクロールさせる。

**Comment by so-asano** [comment]
@baisony 

これでよければ実装してみます。ほかにアイデアがあったら提案してください。

**Comment by baisony** [comment]
@so-asano こちらの仕様で機能の実装、よろしくお願いいたします。
