### ISSUE TITLE
フィードジェネレータの読み込みが遅い

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#259]
- ピンどめしたフィードジェネレータの読み込みに時間がかかり、メニューの表示が遅いのがストレスになる。
- ピンどめしたフィードジェネレータの名前と uri をキャッシュしておけばいいのではないか。
- 変更される頻度はそれほどないはずなので、ユーザは違和感なく使えるとかんがえられる。

**Comment by baisony** [comment]
これら全て一旦解決されたと思われますのでクローズします。
また再度問題がありましたらイシュー立てを行います
