### ISSUE TITLE
一度選んだ挙動をキャンセルするときの方法を簡便にしてほしい

### ISSUE THREAD

**Issue by nostr-bluesky** [baisony/ucho-ten#26]
Cancelボタンを押すではなく，画面のあいてるところを押すとダイアログが消えるなど．

特に投稿画面．

**Comment by baisony** [comment]
@nostr-bluesky スマホにおける空き領域はソフトウェアキーボードを引っ込める時に使えるので、一長一短なのですが何かしらの方法を考えてみます。

**Comment by baisony** [comment]
@nostr-bluesky いろいろ改善はおこなったため、さらにフィードバックがあるようなら別途イシューを立てていただければと思います。
