### ISSUE TITLE
prettier導入によってvercelへのデプロイエラーが出てしまっている

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#29]
@so-asano 
prettier導入によってvercelへのデプロイエラーが出てしまっているので、修正をお願いしてもいいですかー

<img width="1205" alt="スクリーンショット 2023-10-07 13 51 26" src="https://github.com/baisony/ucho-ten/assets/146979022/28099fe6-4f22-4c1c-bebb-257e05c169f1">

**Comment by so-asano** [comment]
@baisony 

コミットメッセージに番号を書き忘れたのですが、`origin/fix/build-error` ブランチにて対応しました。

**Comment by so-asano** [comment]
@baisony 

こちらクローズできますかね？

**Comment by baisony** [comment]
マージしたのでクローズいたします。
