### ISSUE TITLE
アバター画像のサイズが小さいことがある

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#295]
- おそらくは `displayName` などが長すぎて圧縮されてしまっている。

![image](https://github.com/baisony/ucho-ten/assets/770175/36954159-9f9d-4d6d-8f63-560fc0aeea92)

別件として、`displayName` と `handle` の文字列が時間表示ににかぶっている件にも対応する必要がある。

**Comment by baisony** [comment]
本件は修正しました。
ただ、displayNameとhandleについては別issueを立てます。
