### ISSUE TITLE
個別ポスト画面の Author's と Other's の仕様を明確にしてほしい

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#305]
- どういう仕様を考えているのかがわからない。
- 言葉としても "Author's" に対して "Other's" はおかしいのではないか（"Others'" が正しい？）。

**Comment by baisony** [comment]
@so-asano 
others'のスペルミスについては見逃していただくとして、

ただ、有頂天のコンセプトに、他の人のリプライが見えてしまうothers’があって良いのか分からないので、とりあえずは両方実装してから考えます。

### 共通
getPostThreadで取得する

## 個別ポストページの仕様
### author's
- reply rootやparentがあれば上に表示する
- そのpostについたreplyがあれば下に表示するが、表示するものはparentやroot、authorのみ(ネストされたもの)
- それ以外の人は表示しない

### others'
- reply rootやparentがあれば上に表示する
- そのpostについたreplyは全て表示する(第１層のみ)


不明点等ありましたら教えてください。
