### ISSUE TITLE
ViewPostCard にて、引用ポストの表示で、削除済みのポストを引用しているポストを表示するタイミングでエラー表示がでる

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#306]
## 現象

タイムラインやフィードの表示時に、削除済みポストを引用しているポストを表示させようとすると、このようなエラー表示が出る。

![image](https://github.com/baisony/ucho-ten/assets/143017/2dd0d231-23cf-43d6-aa3b-28fafa46a902)

このとき、`postJsonData`は、通常のポストレコードの内容ではなく、

```json
{
    "$type": "app.bsky.embed.record#viewNotFound",
    "uri": "at://did:plc:bb6dwuy4ehui3k7isvv73fpc/app.bsky.feed.post/3kd3mqn75ox2z",
    "notFound": true
}
```

となっている。

このエラーが起こったポストの例は、

https://bsky.app/profile/moja.blue/post/3kd3msqyphx2z

## 望まれる動作

エラー表示がでずに、引用元が削除済みの引用ポストとして表示させるか、当該の引用ポスト自体を表示しないか。
有頂天の考えに従って、適切な対応が必要です

**Comment by baisony** [comment]
こちら、 #302 にて対応済ですのでクローズいたします。
