### ISSUE TITLE
一つあたりのミュートワードに文字数制限をつける検討

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#307]
バックエンドと通信するのであれば、制限かけておいた方が安心かなと

**Comment by henoya** [comment]
### バックエンド側での文字数制限に関する制限の考え方

無制限な長さの文字列を許容すると、もちろん保存できるデータ容量の問題が発生します。
ただし、選択する保存先によって異なりますが、実際には例えば32kbとか、実用上は問題ないサイズだったりもします。
32kb = 32768バイト、UTF-8 通常の日本語文字3バイトだと 10922 文字、絵文字だと4バイトなどで 8192 文字、複合文字を考えても 6バイトで 5461文字など。

事実上、ミュートワードとして考えられるのが、ポストの本文全文対象としても 300文字なので、バックエンドとしての制限は、ほとんど無視できるかと。

### ミュートワードの文字数制限として考慮すべき要素

- ミュートワードを入力するUI上の、入力可能文字数
- ミュートワードを確認表示するときの、画面表示の時に見苦しくならない文字数、もしくは表示方法

もう一つ、ミュートワードは、ポストテキスト中の文字列に完全一致でいいのかどうか、英単語などの大文字小文字対応をどうするかなど、実際の処理上の機能要件を洗い出す必要があります。

**Comment by henoya** [comment]
この内容に関しては、Discussion で検討するのがいいのではないかと思います。

**Comment by baisony** [comment]
上限について
文字数20文字
設定可能数30個
