### ISSUE TITLE
古い通知が inbox に取得できていない

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#33]
- 原因不明のため、とりあえず調査をおこなう。

**Comment by so-asano** [comment]
@baisony 

- `InfiniteScroll` の実装に若干問題があった。
- 独自のフィルターをかけているため、通知数が極端に少なくなることがあった。

修正しましたので、確認お願いします。

`InfiniteScroll` の実装にはやや誤りがあるのでほかも修正しようとおもうのですが、いかがでしょうか？

**Comment by so-asano** [comment]
@baisony 

`InfiniteScroll` の実装の修正によりローダーの表示が可能になったのでローダーの表示を追加しました。

**Comment by baisony** [comment]
@so-asano 
こちらの修正を確認いたしましたので、クローズいたします。
