### ISSUE TITLE
提案：Discussion を有効にして、使用検討などに使用しては

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#341]
Issue の内容によっては、使用の詳細検討などが必要に鳴る場合もありますので、Discussion を有効にして、使用して見てはどうでしょうか。

**Comment by baisony** [comment]
@henoya さん
先ほどDiscussionを有効にしてみましたので、徐々に使用してみる方向性にいたします。
ご提案いただきありがとうございます。
