### ISSUE TITLE
提案：Dependabot を設定して、依存パッケージの更新をおこないませんか

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#342]
GitHub の機能の、Dependabot により、定期的に、依存パッケージの更新や、脆弱性の発見されたパッケージバージョンに対するalertなどを出してくれます。
また、そのときに、パッケージ更新のプルリクを作成してくれたりもします。

依存パッケージを最新にしておくのは、のちに問題が起きて数世代前の古いバージョンからの以降が発生することを考えると、定期的に更新しておいた方がいいと思います。

**Comment by baisony** [comment]
@henoya 
セキュリティアップデートのプルリク自動作成機能と、シークレットキーpush防止を有効にしてみました。
ご提案いただきありがとうございました。

**Comment by henoya** [comment]
できれば、最後の通常のパッケージアップデートの指定もして欲しいです。というか、これが目的。
1週間に1どでいいですので。

**Comment by baisony** [comment]
@henoya 
update dailyとしているので毎日チェック設定のつもりですが、どうやらそうなっていないようでして、.ymlをどのように編集したら良いか、あるいはプルリクを作成していただいて、henoyaさんに更新設定をお願いしたいのですが可能でしょうか

**Comment by henoya** [comment]
@baisony 見てみます

**Comment by henoya** [comment]
pnpm ではなくて npm にする手もありそうですが、デプロイ時に問題でそうですね。
そもそもが、仕様パッケージの新バージョンが公開された時に実行されるので、ふるいままで新しいのもしばらく出てないと出ないですね。

**Comment by baisony** [comment]
@henoya nextjs13か何かのデフォルトがpnpmだったような気がしますので、そこは続行で行きたいのですが、何か不都合等あるのでしょうか？

**Comment by henoya** [comment]
いや別にないです。
多分一旦落ち着いた時にパッケージアップデートしといた方がいいでしょうね。
Dependamtbot も新しいパッケージになった時しか通知しないみたいなんで。

**Comment by baisony** [comment]
当面の方針として、手動で依存パッケージの更新を行うこととします。

なお、dependaBotの運用については、ATPやNext.jsが安定してからとします。
