### ISSUE TITLE
Infinite Scroll の実装を修正する

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#35]
- 既存の実装は正しくないので修正すべき。

**Comment by so-asano** [comment]
@baisony 

ついでに New Posts タップ時にトップにスクロールするよう変更しました。関連イシューは #1 です。

**Comment by baisony** [comment]
こちらの修正を確認しましたので、クローズといたします。

**Comment by so-asano** [comment]
@baisony 

すみません、誤解があったようで。まだ全部の `InfiniteScroll` は修正できてないんですよ。
再オープンします。

**Comment by baisony** [comment]
こちら、すでに修正を確認 & マージ済みですので、クローズいたします。
