### ISSUE TITLE
提案:リスケを視野に入れませんか

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#355]
リファクタリングやプルリクのコードレビューの件にも絡んできますが、**間に合わせにしますか**それとも**ちょっとはマシなもの**を目指しますか？

あと、必要な機能、必要でない機能ははっきりしていますか？
そのために必要な作業はあと何が残ってますか？

リファクタリングとかコードレビューする時間あったら、完成させる時間につぎ込みたい、という考えもあります。

今のペースで間に合いますか？
間に合わない場合どうしますか？

**Comment by henoya** [comment]
追記

これは僕自身の役割についての考えでもあります。
僕のここで期待される役割が全体の質の底上げとすると、そのためにはどうしても時間をかけないといけないタスクしか出てきません。
その中で、リリース優先でと言われると、自分としては不完全燃焼にならざるをえません。

自分が参加している意義は？などネガディブな方向になっています。

**Comment by baisony** [comment]
@henoya 
返信遅くなりました。

指揮不足によってダレてきいる今、何をすべきで、何を後回しすべきか。自分がどういうポジションで何を支持すべきか、何を優先事項とすべきか、ということについて1日考えておりました。

特にリファクタリングには時間も労力もかかると思います。
後々を考えると、本来は最初から綺麗なコードを書きつつ、フォルダ構成についても十分議論してから設計すべきでした。

結論としては、今最優先すべきは、issueに上がっているバグ修正と機能を実装することが第一だと思います。


役割など、「わからない」を理由としてなあなあにしてきたのは僕の責任です。大変申し訳ございませんでした。
(続きます。)

**Comment by baisony** [comment]
@henoya 
特に現状henoyaさんの役割としている品質管理とその向上について、
私は、今はその作業に取り掛かっていただくフェーズにいないと判断しました。

機能すらほぼ完全に実装されていないのにも関わらず、不完全な状態における品質向上に関わる作業をしていただいても、全体を考えた時に結果的に無駄なリソースが割かれていたことになると思います。

ですので、リファクタリング、他の最適化作業?(機能実装に伴うものは別として)については一旦の作業を停止していただきますでしょうか。申し訳ありません。
(続きます)

**Comment by baisony** [comment]
@henoya 
### 期限について
11日(10日？)がベータ版完成のリミットとなっております。(本リリースは月末を想定)
リファクタリングや最適化は前述の通り、今やるべきことではなく、βリリース以降にやるべきことだと思っています。

私の責任ではありますが、せっかく参画していただいているのに、各々の作業に意義を持っていただけていただけていない状況でしょう。

そこで、ダラダラ期限を伸ばすのではなく、ケジメとして一旦の〆切を11日から変更しない方針で行きます。
ただし、その分遅れを取り戻させるといった考えはなく、
・やること
・やりたいこと
・今やるべきこと
これらを分解し、総合的に判断した結果、当初予定していた必要な作業を各自に行っていただきたく思います。
また、11日に間に合わず、あぶれた機能に関しては責任もって私が実装作業に取り組みます。

### 必要な作業と機能
現時点でいくつかの抜けを確認しておりますが、こちらは概ねissueに上げている内容です。
今日中には列挙しきっておきます。

### 期待する作業
まずは前に進むために、henoyaさんにはバックエンドの実装とそれの連携についての作業をお願いしたいです。

今、最低限バックエンドを実装してやりたいことの内容としましては、

- ミュートワードの同期
- ブックマークの同期
です。

こちらにつきまして、仕様の確認などを行い実装になると思われます。

それに際して必要かつ足りていない前提情報がそもそも何かを明確にし、それを両者間で共有しながらの開発になりますが、このような方針で作業していただくことは可能でしょうか。
