### ISSUE TITLE
ユーザ検索でユーザのカードの表示に問題がある

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#38]
以下のような問題がある:

- ダークモードにしか対応していない。
- モバイルでアバターが表示されない。
- プロフィールテキストが右にはみでる。

**Comment by so-asano** [comment]
@baisony 

検索のところ開発しててテンション下がるので対応おねがいします。

**Comment by baisony** [comment]
@baisony 手が空いた時に修正しておきますー。

**Comment by baisony** [comment]
@so-asano 
すみませんブランチ分けるの忘れてました！
列挙された問題に関しては全て改善・修正を行いましたので、クローズいたします。
