### ISSUE TITLE
提案：バックエンド同期に使う DB について

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#383]
## ワードミュートとブックマークのバックエンド同期の実装について

関連 Discussion ワードミュートおよびブックマークのバックエンド同期について #348

## 提案内容

@baisony 
詳しくは Discussion #348 に書きますので、検討も Discussion の方で行えればと思います。

- TiDB Cloud Serverless を使用しようと考えている
- 当初の仕様では、ワードミュートとブックマークを分けて保存する意向があったが、その意図は
- `last_loggedin` みたいな記録を取る必要はないか

**Comment by baisony** [comment]
$403 にて実装済みですのでクローズいたします。
