### ISSUE TITLE
特定のフィードで無限再描画が起きる

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#415]
## 現在確認できているカスタムフィード

- golang
  - https://bsky.app/profile/did:plc:26eoqvsiov3hmsfqruoi4d3s/feed/aaaid2c3aam4w

## 現象

最初の表示、もしくは何度か追加読み込みをおこなうと、無限再描画のエラーがでる。

おそらくはそのフィードに出てきやすいポストの特性によって決まるのだと思われます。

**Comment by henoya** [comment]
リンクカードがたくさんあるからかも？

**Comment by henoya** [comment]
もしかしたら
FeedPage.tsx

```typescript
if (posts.length === 0 && cursor === "") setIsEndOfFeed(true)
```

の&&を||に変えると治るかもしれません・・・！

エラーがでなくなりました

**Comment by baisony** [comment]
こちら、空の配列か、あるいはカーソルが""の状態で降ってくることのどちらか(おそらく後者)が問題となりますので or とすることで対処しました。
