### ISSUE TITLE
フィードごとにスクロール位置とcursorの値の管理を個別にした方がいい

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#416]
## 別のフィードでの追加読み込みなどで、フィードに戻った時に先頭に戻ったりする

フィード名と組でuseMemoなどで記憶管理した方が良さそう

**Comment by baisony** [comment]
@henoya さん
#500 にてスクロール位置の管理を実装しました。
ご提案いただき、ありがとうございました。
