### ISSUE TITLE
リプライポスト画面におけるポスト本文の前後の空白と改行の扱いに問題がある

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#46]
- ~~残り字数の計算でポスト本文の前後の空白と改行が考慮されてしまっている。~~
修正済み

**Comment by baisony** [comment]
@henoya 
本件とはあまり関係がないですが、リプライモーダルにおいて複数の問題がありまして、
・lightモードにおいて、リプライ先のViewPostCardの背景色が見えてしまっている
→ViewPostCardで、lightモードの時に背景色を透明にすると修正できます
・リプライラインが貫通している
→PostModalにViewPostCardを乗っける際はパディングかマージンTopを0にすると貫通を防げます。

以上、二つの問題についても合わせて修正してくださると嬉しいです。

Lightモード
![スクリーンショット 2023-10-10 15 44 04](https://github.com/baisony/ucho-ten/assets/146979022/2b90ddba-20b8-4910-b51e-dbe258aea5ae)

Darkモード

![スクリーンショット 2023-10-10 15 45 06](https://github.com/baisony/ucho-ten/assets/146979022/a42c8a22-6ba5-46df-81a2-eec8cbc84146)

**Comment by baisony** [comment]
すみません追加です。
右上にうっすらと閉じるボタンが見えてしまっているので、そちらを削除していただけたら嬉しいです。

**Comment by baisony** [comment]
以上の追加の問題は #130 と#131 に移動いたしました。
クローズいたします。
