### ISSUE TITLE
最近の機能追加や修正以降の各種不具合の対応

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#47]
- [x] ホーム画面のヘッダからカスタムフィードが読み込めなくなっている。
- [x] ホーム画面のフィードで相対時間の表示が進まなくなっている。
- [x] ホーム画面のヘッダの上部タブの選択状態が不正である。

随時追記する予定。

**Comment by baisony** [comment]
検索画面における、初心者への導線の作成
(フィード検索やJapanese Clusterへの誘導など)
