### ISSUE TITLE
画像の拡大機能の実装

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#5]
- ~~PCからみた場合において、矢印が比較的小さく、クリックするのに多少ストレスがかかるため、もう少し大きくすることと、矢印に対してrounded-full bg-black bg-opaticy-50あたりで背景色を設定してあげると、矢印が目立って良いかも~~(修正の必要無いと判断)

- ~~画像が一枚の場合でも無限にスクロールできてしまう点は要修正~~

- ~~ピンチやダブルタップによるズームの実装（可能であれば）。~~
- ~~Alt Text の表示（できることが望ましい）。~~

- (特にスマホでは)閉じるボタンを都度押すのはストレスなので下スワイプをすると閉じられる仕様が好ましい。
- ~~画像でないところをクリックしたときも同様に閉じられるようにしたい。~~

**Comment by so-asano** [comment]
@baisony 

ズームを実装しました。

**Comment by so-asano** [comment]
@baisony 

Alt Text の表示を実装しました。たぶんうまくいってるはず。

**Comment by so-asano** [comment]
@baisony 

- 画像が 1 枚の場合に左右スクロール不可、移動ボタン非表示としました。
- イシューに記述はありませんでしたが、カウンターを追加してみました。あったほうがいいかなと。

**Comment by so-asano** [comment]
@baisony 

残タスクの対応よろしくお願いします。

**Comment by baisony** [comment]
@so-asano 
はい。

では、一旦現在の状態をマージいたします。

**Comment by baisony** [comment]
こちら、実装が終わりましたのでクローズといたします。
また、上スワイプにて閉じるは別の機会に実装といたします。
