### ISSUE TITLE
ポスト画面 / リプライモーダルにおける画像添付機能に向けて

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#55]
・画像圧縮ライブラリの選定
条件
・あげたい画像の画質をできればあまり落とさず、上限サイズ975KBのギリギリを攻めたい

以上、よろしくお願いします

**Comment by so-asano** [comment]
@baisony 

これって速度とかも重視しなければいけないですよね？ 画質が最重要ということだとおもいますが。

**Comment by baisony** [comment]
@so-asano 
圧縮処理はポストを送信する直前にするつもりなので、速度はあまり重視してません。画質最優先です。

**Comment by baisony** [comment]
こちら、画像添付機能の実装が終わりましたのでクローズいたします。
