### ISSUE TITLE
ポストの画像添付機能の実装

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#56]

**Comment by baisony** [comment]
画像が4枚以上あるのに添付ボタンが無効にならない問題をついでに修正します

**Comment by so-asano** [comment]
@baisony 

基本的な部分の実装はおこないました。残りのエラー表示の実装について、対応をお願いします。

**Comment by baisony** [comment]
ブランチ切る & pushするの忘れてて同じコミットとなってしまいました・・・。
こちら、合計5枚以上添付以上すると無反応とすることにしました。
また、いい案が浮かばなかったため、一時的にn/4表示をいたしました。
