### ISSUE TITLE
ポスト本文の IME 変換中の文字列が二重になって投稿される

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#59]
再現手順:

- ポスト画面に遷移。
- 日本語 IME 環境で文字を入力し、変換を確定しない状態にしておく。
- ポストをおこなう。
- 変換が確定されていない文字列がポスト本文に 2 重に入っている。

**Comment by baisony** [comment]
こちらは調査後、原因が分かり次第取り掛かります。

**Comment by so-asano** [comment]
@henoya 

こちら henoya さんの環境で再現しますか？ また、もし原因について心当たりがあったら教えていただけるとたすかります。

**Comment by so-asano** [comment]
この現象だとおもわれる:

- https://qiita.com/zaru/items/3c504211e67a2bb10ca9
