### ISSUE TITLE
タブバーボタンの選択状態が消えることがある

### ISSUE THREAD

**Issue by baisony** [baisony/ucho-ten#6]
再現方法:

1. ホームかインボックスのいずれかのタブに遷移。
2. ポストボタンをタップ。
3. キャンセルボタンをタップ。
4. タブバーの選択状態が消えている。また、ヘッダの表示も正しくない。

**Comment by so-asano** [comment]
@baisony 

本件、いちおう修正したんですが、コードの内容が謎なところがあるので、その点ご相談させてください。

**Comment by baisony** [comment]
@so-asano 
本件の修正を確認しました。
また、すでにマージ済みのようですので、クローズいたします。
