### ISSUE TITLE
新 UI 導入の技術検証をおこなう

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#74]
目的:

- 画面をスワイプして左右にページングする公式 Bluesky クライアントのような UI の実装が現実的に可能かどうかを検証し、可能であれば最終的には main へのマージを目指す。

検証する技術:

- Swiper による左右スワイプでのページング。
- Virtuoso による再利用リストビュー。
- （Lazy Loading による遅延表示）

追記:
Nirvana UI？ っていう名前になるらしい。

**Comment by baisony** [comment]
こちら、一旦mainへmergeしましたのでクローズいたします。
