### ISSUE TITLE
タイムラインから個別のスレッドを表示してからタイムラインに戻ると、タイムラインが再読込される

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#76]
## 現象

以下の手順で起こります

- タイムラインを表示して、下にある程度スクロールする
- いずれかのポストをクリックし、そのポストのスレッドが表示される。
- タイムラインに「戻る」ボタンの機能で戻ると、タイムラインが再取得され、タイムラインの先頭が表示される

まだスマホ画面では試していないので、PCで「戻る」ボタン機能でタイムラインに戻ること自体がイレギュラーと考えられるのかもしれませんが。

### 期待する挙動

別画面からタイムライン表示に戻った時には、タイムラインの再取得するのはともかく、タイムラインの表示位置は保っておいた方がいいと思います。

**Comment by baisony** [comment]
TanStackQuery で解決するためクローズいたします。
