### ISSUE TITLE
ログインしていない初回アクセスで、ログイン画面の前にタイムラインのスケルトンが表示される

### ISSUE THREAD

**Issue by henoya** [baisony/ucho-ten#77]
## 現象

ログインしていない、初回アクセスの場合に、最初にタイムラインのスケルトンが表示された後に、ログイン画面が表示される。

## 期待される動作

未ログインの場合、タイムラインのスケルトン表示ではなく、ログイン画面がでてほしい。

**Comment by baisony** [comment]
#200 にて対応しますのでクローズいたします。
