### ISSUE TITLE
フィードのロード失敗、取得したポストがゼロの状態の表示が必要

### ISSUE THREAD

**Issue by so-asano** [baisony/ucho-ten#93]
問題:

- 現在だとロード中（スケルトン表示）か取得したものを表示する画面（取得ゼロの場合もある）しかない。
- ユーザはフィードがロード中なのかロードに失敗したのかどうかがわからない（特にフィードジェネレータの場合に顕著）。
- 取得できたポストが 0 の場合、ユーザは真っ白なページをみつめることになる。

**Comment by so-asano** [comment]
@baisony 

対応案の検討をお願いします。

**Comment by baisony** [comment]
@so-asano 
1.と2. についてはどうにかしたいのですが、今はいい案が思いつかないので、思いついたら追加でコメントします。
3については、「ナイヨー」というニュアンスを含んだ文言、あるいはそのような画像を挿入する方針でいきましょう。

**Comment by so-asano** [comment]
@baisony 

> 3については、「ナイヨー」というニュアンスを含んだ文言、あるいはそのような画像を挿入する方針でいきましょう。

たしかフィードジェネレータは任意の文字列を返すので、それの表示は最低限必要かなとおもいます。

**Comment by baisony** [comment]
#221 で対応するためクローズいたします。
